name: beta_sms_mobile
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  go_router: ^13.1.0
  hooks_riverpod: ^2.4.9
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  logging: ^1.2.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Gibson
      fonts:
        - asset: assets/fonts/GraphikRegular.otf
          weight: 500
        - asset: assets/fonts/GraphikBold.otf
          weight: 700
        - asset: assets/fonts/GraphikLight.otf
          weight: 300
        - asset: assets/fonts/GraphikMedium.otf
          weight: 400
        - asset: assets/fonts/GraphikSemiBold.otf
          weight: 600
        - asset: assets/fonts/GraphikThin.otf
          weight: 200
